import pathlib
p = pathlib.Path('e:/Proj/AgentProj/src/agent/emotion.py')
L = p.read_text('utf-8').split(chr(10))
a = chr(34987)+chr(20882)+chr(29359)+chr(12289)+chr(24868)+chr(24626)
s = chr(31616)+chr(30701)+chr(12289)+chr(19981)+chr(24819)+chr(22810)+chr(35828)
N = []
N.append('        constraints = self.get_hard_constraints()')
N.append('        boundary = self._last_result.boundary_violation if self._last_result else False')
N.append('')
N.append('        if boundary:')
N.append('            response_style = "'+a+'"')
N.append('            emotional_density = 0.9')
N.append('            emoji_tendency = 0.1')
N.append('            proactive_prob = 0.0')
N.append('            topic_preference = []')
N.append('        elif constraints.get("short_replies"):')
N.append('            response_style = "'+s+'"')
N.append('        if constraints.get("proactive_disabled"):')
N.append('            proactive_prob = 0.0')
N.append('        if constraints.get("refuse_tools"):')
N.append('            proactive_prob = 0.0')
N.append('')
N.append('        return {')
N.append('            "emotional_density": round(min(emotional_density, 1.0), 2),')
N.append('            "emoji_tendency": round(min(max(emoji_tendency, 0.0), 1.0), 2),')
N.append('            "response_style": response_style,')
N.append('            "topic_preference": topic_preference,')
N.append('            "proactive_prob": round(min(max(proactive_prob, 0.0), 1.0), 2),')
N.append('            "refuse_tools": constraints.get("refuse_tools", False),')
N.append('            "short_replies": constraints.get("short_replies", False),')
N.append('            "boundary_violation": boundary,')
N.append('        }')
L[333:346] = N
p.write_text(chr(10).join(L), 'utf-8')
print('OK')
