import os

os.makedirs('docs/superpowers/specs', exist_ok=True)

lines = []
lines.append('# LittleGrey Integration Design Specification')
lines.append('')
lines.append('**Date**: 2026-05-15')
lines.append('**Status**: Draft - Pending User Review')
lines.append('**Approach**: Option A - Progressive Integration')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 1. Overview')
lines.append('')
lines.append('### 1.1 Project Goal')
lines.append('Integrate Shinsekai capabilities (multi-modal performance, plugin system, structured dialog, GUI) into LittleGrey while preserving its core advantages (emotion system, relationship system, self-reflection, interest learning, proactive interaction).')
lines.append('')
lines.append('### 1.2 Core Principles')
lines.append('- Retain LittleGrey emotion/relationship/reflection/learning advantages')
lines.append('- Add Shinsekai multi-modal/plugin/structured-dialog/GUI capabilities')
lines.append('- Create unique AI friend with real emotions plus complete performance capability experience')
lines.append('- Progressive integration: existing features remain unaffected')
lines.append('')
lines.append('### 1.3 Integration Goals')
lines.append('1. Multi-modal Performance: Sprites, TTS, ASR, BGM, CG generation')
lines.append('2. Plugin System: Hot-pluggable extensions for LLM/TTS/ASR/Tools')
lines.append('3. Structured Dialog: COT/NARR/CHOICE/STAT markers for different processing')
lines.append('4. GUI Interface: PySide6 chat window + settings center dual-window')
lines.append('')

content = chr(10).join(lines)
encoded = base64.b64encode(content.encode('utf-8')).decode()
print(encoded[:50])
print(f'Length: {len(encoded)}')
